CREATE TABLE IF NOT EXISTS vehicle_classes
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50)  NOT NULL,
    name VARCHAR(100) NOT NULL,
    CONSTRAINT uk_vehicle_classes_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS gates
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50)  NOT NULL,
    name VARCHAR(150) NOT NULL,
    CONSTRAINT uk_gates_code UNIQUE (code),
    CONSTRAINT uk_gates_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS vehicles
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plate            VARCHAR(255)  NOT NULL,
    vehicle_class_id BIGINT        NOT NULL,
    balance          NUMERIC(12,2) NOT NULL DEFAULT 0,
    owner_name       VARCHAR(150)  NOT NULL,
    CONSTRAINT uk_vehicles_plate UNIQUE (plate),
    CONSTRAINT fk_vehicles_vehicle_class
        FOREIGN KEY (vehicle_class_id) REFERENCES vehicle_classes (id)
);

CREATE TABLE IF NOT EXISTS transactions
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gate_id          BIGINT        NOT NULL,
    fee              NUMERIC(12,2) NOT NULL,
    transaction_date TIMESTAMP     NOT NULL,
    vehicle_id       BIGINT        NOT NULL,
    CONSTRAINT fk_transactions_gate
        FOREIGN KEY (gate_id) REFERENCES gates (id),
    CONSTRAINT fk_transactions_vehicle
        FOREIGN KEY (vehicle_id) REFERENCES vehicles (id)
);

CREATE TABLE IF NOT EXISTS tariffs
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gate_id          BIGINT        NOT NULL,
    vehicle_class_id BIGINT        NOT NULL,
    fee              NUMERIC(12,2) NOT NULL,
    CONSTRAINT uk_tariffs_gate_vehicle_class
        UNIQUE (gate_id, vehicle_class_id),
    CONSTRAINT fk_tariffs_gate
        FOREIGN KEY (gate_id) REFERENCES gates (id),
    CONSTRAINT fk_tariffs_vehicle_class
        FOREIGN KEY (vehicle_class_id) REFERENCES vehicle_classes (id)
);

ALTER TABLE vehicles
    ADD COLUMN IF NOT EXISTS vehicle_class_id BIGINT;

ALTER TABLE transactions
    ADD COLUMN IF NOT EXISTS gate_id BIGINT;

DO
$$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'vehicles'
          AND column_name = 'vehicle_class'
    ) THEN
        EXECUTE $sql$
            INSERT INTO vehicle_classes (code, name)
            SELECT 'LEGACY_' || UPPER(SUBSTRING(MD5(TRIM(vehicle_class)) FROM 1 FOR 12)),
                   TRIM(vehicle_class)
            FROM vehicles
            WHERE vehicle_class IS NOT NULL
              AND TRIM(vehicle_class) <> ''
            ON CONFLICT DO NOTHING
        $sql$;

        EXECUTE $sql$
            UPDATE vehicles v
            SET vehicle_class_id = vc.id
            FROM vehicle_classes vc
            WHERE v.vehicle_class_id IS NULL
              AND v.vehicle_class IS NOT NULL
              AND vc.code =
                  'LEGACY_' || UPPER(SUBSTRING(MD5(TRIM(v.vehicle_class)) FROM 1 FOR 12))
        $sql$;
    END IF;
END
$$;

DO
$$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'transactions'
          AND column_name = 'station_name'
    ) THEN
        EXECUTE $sql$
            INSERT INTO gates (code, name)
            SELECT 'LEGACY_' || UPPER(SUBSTRING(MD5(TRIM(station_name)) FROM 1 FOR 12)),
                   TRIM(station_name)
            FROM transactions
            WHERE station_name IS NOT NULL
              AND TRIM(station_name) <> ''
            ON CONFLICT DO NOTHING
        $sql$;

        EXECUTE $sql$
            UPDATE transactions t
            SET gate_id = g.id
            FROM gates g
            WHERE t.gate_id IS NULL
              AND t.station_name IS NOT NULL
              AND g.code =
                  'LEGACY_' || UPPER(SUBSTRING(MD5(TRIM(t.station_name)) FROM 1 FOR 12))
        $sql$;
    END IF;
END
$$;

ALTER TABLE vehicles
    ALTER COLUMN balance TYPE NUMERIC(12,2) USING balance::NUMERIC(12,2),
    ALTER COLUMN vehicle_class_id SET NOT NULL;

ALTER TABLE transactions
    ALTER COLUMN fee TYPE NUMERIC(12,2) USING fee::NUMERIC(12,2),
    ALTER COLUMN gate_id SET NOT NULL;

DO
$$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uk_vehicle_classes_code'
          AND conrelid = 'vehicle_classes'::regclass
    ) THEN
        ALTER TABLE vehicle_classes
            ADD CONSTRAINT uk_vehicle_classes_code UNIQUE (code);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_vehicles_vehicle_class'
          AND conrelid = 'vehicles'::regclass
    ) THEN
        ALTER TABLE vehicles
            ADD CONSTRAINT fk_vehicles_vehicle_class
                FOREIGN KEY (vehicle_class_id) REFERENCES vehicle_classes (id);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_transactions_gate'
          AND conrelid = 'transactions'::regclass
    ) THEN
        ALTER TABLE transactions
            ADD CONSTRAINT fk_transactions_gate
                FOREIGN KEY (gate_id) REFERENCES gates (id);
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS ix_vehicles_vehicle_class_id
    ON vehicles (vehicle_class_id);

CREATE INDEX IF NOT EXISTS ix_transactions_gate_id
    ON transactions (gate_id);

CREATE INDEX IF NOT EXISTS ix_transactions_vehicle_id
    ON transactions (vehicle_id);

CREATE INDEX IF NOT EXISTS ix_tariffs_gate_id
    ON tariffs (gate_id);

CREATE INDEX IF NOT EXISTS ix_tariffs_vehicle_class_id
    ON tariffs (vehicle_class_id);
